version: "3.8"
services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DATABASE_NAME=<name>
      - DATABASE_USER=<user>
      - DATABASE_PASSWORD=<password>
      - DATABASE_HOST=<host>
      - DATABASE_PORT=<port>

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    environment:
      - API_BASE_URL=http://127.0.0.1:8000/
    ports:
      - "3002:3000"
